### ISSUE TITLE
interesting

### ISSUE THREAD

**Issue by g0ldyy** [JijaProGamer/BrawlStarsAIlatest#1]
Hey!
This project seems very interesting, do you have a discord server or something to talk?

Have a great day.

**Comment by JijaProGamer** [comment]
The project is still WIP,  In a week or two it'll become public and get documentation, I'll make a ping here then.

P.S, it'll require a external Android phone connected by USB, a computer with at least 8GB (preferably high transfer, DDR4 3200mhz or higher), a I5 12600k or higher, and possibly in the future a gtx 1050 ti or higher
